# Generated by Django 4.2.11 on 2025-09-03 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.folders')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.folders')),
            ],
        ),
    ]
