# Generated by Django 4.2.11 on 2025-09-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.groups'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.groups'),
        ),
    ]
