# Generated by Django 4.2.11 on 2025-09-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_groups_alter_bookmarks_group_alter_folders_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='folders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
