# Generated by Django 4.2.11 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmarks_id_alter_folders_id_alter_groups_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='url',
            field=models.URLField(default='', max_length=400),
        ),
    ]
