# Generated by Django 4.2.11 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmarks_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
